"""Canonical Clockify manifest data shared across runtime and tests."""
from __future__ import annotations

from collections import defaultdict
from typing import Dict, List

# Reference list of every Clockify webhook event supported by the marketplace.
# Source: Clockify_Webhook_JSON_Samples.md and marketplace manifest schema docs.
CLOCKIFY_WEBHOOK_EVENTS = (
    "APPROVAL_REQUEST_STATUS_UPDATED",
    "ASSIGNMENT_CREATED",
    "ASSIGNMENT_DELETED",
    "ASSIGNMENT_PUBLISHED",
    "ASSIGNMENT_UPDATED",
    "BALANCE_UPDATED",
    "BILLABLE_RATE_UPDATED",
    "CLIENT_DELETED",
    "CLIENT_UPDATED",
    "COST_RATE_UPDATED",
    "EXPENSE_CREATED",
    "EXPENSE_DELETED",
    "EXPENSE_RESTORED",
    "EXPENSE_UPDATED",
    "INVOICE_UPDATED",
    "LIMITED_USERS_ADDED_TO_WORKSPACE",
    "NEW_APPROVAL_REQUEST",
    "NEW_CLIENT",
    "NEW_INVOICE",
    "NEW_PROJECT",
    "NEW_TAG",
    "NEW_TASK",
    "NEW_TIMER_STARTED",
    "NEW_TIME_ENTRY",
    "PROJECT_DELETED",
    "PROJECT_UPDATED",
    "TAG_DELETED",
    "TAG_UPDATED",
    "TASK_DELETED",
    "TASK_UPDATED",
    "TIMER_STOPPED",
    "TIME_ENTRY_BATCH_DELETED",
    "TIME_ENTRY_DELETED",
    "TIME_ENTRY_RESTORED",
    "TIME_ENTRY_SPLIT",
    "TIME_ENTRY_UPDATED",
    "TIME_OFF_REQUESTED",
    "TIME_OFF_REQUEST_APPROVED",
    "TIME_OFF_REQUEST_REJECTED",
    "TIME_OFF_REQUEST_WITHDRAWN",
    "USER_ACTIVATED_ON_WORKSPACE",
    "USER_DEACTIVATED_ON_WORKSPACE",
    "USER_DELETED_FROM_WORKSPACE",
    "USER_EMAIL_CHANGED",
    "USER_GROUP_CREATED",
    "USER_GROUP_DELETED",
    "USER_GROUP_UPDATED",
    "USER_JOINED_WORKSPACE",
    "USER_UPDATED",
    "USERS_INVITED_TO_WORKSPACE",
)

# Mapping from event type -> manifest route (relative path, without base URL).
CLOCKIFY_WEBHOOK_ROUTE_MAP = {
    "NEW_TIME_ENTRY": "/webhooks/time/new",
    "TIME_ENTRY_UPDATED": "/webhooks/time/updated",
    "TIME_ENTRY_DELETED": "/webhooks/time/deleted",
    "TIME_ENTRY_RESTORED": "/webhooks/time",
    "TIME_ENTRY_SPLIT": "/webhooks/time",
    "TIME_ENTRY_BATCH_DELETED": "/webhooks/time",
    "NEW_TIMER_STARTED": "/webhooks/time",
    "TIMER_STOPPED": "/webhooks/time",
    "NEW_PROJECT": "/webhooks/project/new",
    "PROJECT_UPDATED": "/webhooks/project/updated",
    "PROJECT_DELETED": "/webhooks/project/deleted",
    "USER_UPDATED": "/webhooks/user/updated",
    "USER_ACTIVATED_ON_WORKSPACE": "/webhooks/user",
    "USER_DEACTIVATED_ON_WORKSPACE": "/webhooks/user",
    "USER_DELETED_FROM_WORKSPACE": "/webhooks/user",
    "USER_JOINED_WORKSPACE": "/webhooks/user",
    "USER_EMAIL_CHANGED": "/webhooks/user",
    "EXPENSE_CREATED": "/webhooks/expense/created",
    "EXPENSE_UPDATED": "/webhooks/expense/updated",
    "EXPENSE_DELETED": "/webhooks/expense/deleted",
    "EXPENSE_RESTORED": "/webhooks/expense",
    "NEW_CLIENT": "/webhooks/generic",
    "CLIENT_UPDATED": "/webhooks/generic",
    "CLIENT_DELETED": "/webhooks/generic",
    "NEW_TAG": "/webhooks/generic",
    "TAG_UPDATED": "/webhooks/generic",
    "TAG_DELETED": "/webhooks/generic",
    "NEW_TASK": "/webhooks/generic",
    "TASK_UPDATED": "/webhooks/generic",
    "TASK_DELETED": "/webhooks/generic",
    "ASSIGNMENT_CREATED": "/webhooks/assignment/created",
    "ASSIGNMENT_UPDATED": "/webhooks/assignment/updated",
    "ASSIGNMENT_DELETED": "/webhooks/assignment/deleted",
    "ASSIGNMENT_PUBLISHED": "/webhooks/assignment",
    "APPROVAL_REQUEST_STATUS_UPDATED": "/webhooks/approval/status-updated",
    "NEW_APPROVAL_REQUEST": "/webhooks/approval",
    "BALANCE_UPDATED": "/webhooks/balance",
    "BILLABLE_RATE_UPDATED": "/webhooks/rate",
    "COST_RATE_UPDATED": "/webhooks/rate",
    "INVOICE_UPDATED": "/webhooks/invoice",
    "NEW_INVOICE": "/webhooks/invoice",
    "LIMITED_USERS_ADDED_TO_WORKSPACE": "/webhooks/workspace",
    "USERS_INVITED_TO_WORKSPACE": "/webhooks/workspace",
    "USER_GROUP_CREATED": "/webhooks/user-group",
    "USER_GROUP_UPDATED": "/webhooks/user-group",
    "USER_GROUP_DELETED": "/webhooks/user-group",
    "TIME_OFF_REQUESTED": "/webhooks/timeoff",
    "TIME_OFF_REQUEST_APPROVED": "/webhooks/timeoff",
    "TIME_OFF_REQUEST_REJECTED": "/webhooks/timeoff",
    "TIME_OFF_REQUEST_WITHDRAWN": "/webhooks/timeoff",
}


def _build_events_by_path() -> Dict[str, List[str]]:
    mapping: Dict[str, List[str]] = defaultdict(list)
    for event, path in CLOCKIFY_WEBHOOK_ROUTE_MAP.items():
        mapping[path].append(event)
    return {path: sorted(events) for path, events in mapping.items()}


CLOCKIFY_WEBHOOK_EVENTS_BY_PATH = _build_events_by_path()

# Canonical list of scopes required for universal read/write access.
# Source: Clockify manifest schema v1.3 (cake marketplace docs).
CLOCKIFY_SCOPE_LIST = (
    "APPROVAL_READ",
    "APPROVAL_WRITE",
    "CLIENT_READ",
    "CLIENT_WRITE",
    "CUSTOM_FIELDS_READ",
    "CUSTOM_FIELDS_WRITE",
    "EXPENSE_READ",
    "EXPENSE_WRITE",
    "GROUP_READ",
    "GROUP_WRITE",
    "INVOICE_READ",
    "INVOICE_WRITE",
    "PROJECT_READ",
    "PROJECT_WRITE",
    "REPORTS_READ",
    "REPORTS_WRITE",
    "SCHEDULING_READ",
    "SCHEDULING_WRITE",
    "TAG_READ",
    "TAG_WRITE",
    "TASK_READ",
    "TASK_WRITE",
    "TIME_ENTRY_READ",
    "TIME_ENTRY_WRITE",
    "TIME_OFF_READ",
    "TIME_OFF_WRITE",
    "USER_READ",
    "USER_WRITE",
    "WORKSPACE_READ",
    "WORKSPACE_WRITE",
    "WORKSPACE_SETTINGS_READ",
    "WORKSPACE_SETTINGS_WRITE",
)
