"""Initial schema with all models

Revision ID: 5978bbfafc2d
Revises: 
Create Date: 2025-11-13 23:36:36.613465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5978bbfafc2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_studio_bootstrap_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_studio_bootstrap_state_workspace_id'), 'api_studio_bootstrap_state', ['workspace_id'], unique=False)
    op.create_table('api_studio_entity_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('endpoint_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_studio_entity_cache_workspace_id'), 'api_studio_entity_cache', ['workspace_id'], unique=False)
    op.create_table('api_studio_flow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_event_types', sqlite.JSON(), nullable=False),
    sa.Column('conditions', sqlite.JSON(), nullable=True),
    sa.Column('actions', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_studio_flow_workspace_id'), 'api_studio_flow', ['workspace_id'], unique=False)
    op.create_table('api_studio_flow_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('webhook_log_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('actions_result', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_studio_flow_execution_flow_id'), 'api_studio_flow_execution', ['flow_id'], unique=False)
    op.create_index(op.f('ix_api_studio_flow_execution_webhook_log_id'), 'api_studio_flow_execution', ['webhook_log_id'], unique=False)
    op.create_index(op.f('ix_api_studio_flow_execution_workspace_id'), 'api_studio_flow_execution', ['workspace_id'], unique=False)
    op.create_table('api_studio_installation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('addon_id', sa.String(length=64), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=False),
    sa.Column('addon_token', sa.String(length=255), nullable=False),
    sa.Column('settings_json', sqlite.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_studio_installation_workspace_id'), 'api_studio_installation', ['workspace_id'], unique=False)
    op.create_table('api_studio_webhook_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('headers', sqlite.JSON(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_studio_webhook_log_workspace_id'), 'api_studio_webhook_log', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_studio_webhook_log_workspace_id'), table_name='api_studio_webhook_log')
    op.drop_table('api_studio_webhook_log')
    op.drop_index(op.f('ix_api_studio_installation_workspace_id'), table_name='api_studio_installation')
    op.drop_table('api_studio_installation')
    op.drop_index(op.f('ix_api_studio_flow_execution_workspace_id'), table_name='api_studio_flow_execution')
    op.drop_index(op.f('ix_api_studio_flow_execution_webhook_log_id'), table_name='api_studio_flow_execution')
    op.drop_index(op.f('ix_api_studio_flow_execution_flow_id'), table_name='api_studio_flow_execution')
    op.drop_table('api_studio_flow_execution')
    op.drop_index(op.f('ix_api_studio_flow_workspace_id'), table_name='api_studio_flow')
    op.drop_table('api_studio_flow')
    op.drop_index(op.f('ix_api_studio_entity_cache_workspace_id'), table_name='api_studio_entity_cache')
    op.drop_table('api_studio_entity_cache')
    op.drop_index(op.f('ix_api_studio_bootstrap_state_workspace_id'), table_name='api_studio_bootstrap_state')
    op.drop_table('api_studio_bootstrap_state')
    # ### end Alembic commands ###
